language: php

cache:
  directories:
    - $HOME/.composer/cache/files

php:
  - 7.4
  - 7.3
  - 8.0snapshot

before_script:
    - phpenv config-rm xdebug.ini
    - composer self-update
    
install:
    - if [ "$TRAVIS_PHP_VERSION" = "8.0snapshot" ]; then composer remove --dev friendsofphp/php-cs-fixer --no-update --no-interaction; fi;
    - composer install --prefer-dist

script:
    - if [ "$TRAVIS_PHP_VERSION" != "8.0snapshot" ]; then vendor/bin/php-cs-fixer fix --dry-run; fi;
    - vendor/bin/phpstan analyze
    - vendor/bin/phpunit
